version: '3'

services:
  proxy:
    image: traefik:latest
    container_name: traefik
    labels: 
      - traefik.enable=true
      - traefik.port=8080
    networks:
      - traefik_network
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme:/etc/traefik/acme

networks:
  traefik_network:
    external: true